- name: Pull repo and recreate docker container
  hosts: all
  tasks:
    - name: Pull changes from git repository
      git:
        repo: https://github.com/School-58-IT-gen-2/research-and-development.git
        dest: /projects/dnd/research-and-development
        version: main

    - name: Build Docker image
      command: docker build -t research_and_development_container:main /projects/dnd/research-and-development

    - name: Stop old container
      command: docker compose -f /projects/dnd/research-and-development/docker-compose.yml down --remove-orphans

    - name: Run docker-compose up
      command: docker compose -f /projects/dnd/research-and-development/docker-compose.yml up -d --force-recreate

